pair/pair/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("reviews.urls")),
]

pair/reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("", views.main, name="main"),
    path("review/", views.review, name="review"),
    path("new/", views.new, name="new"),
    path("create/", views.create, name="create"),
    path("detail/<int:pk>/", views.detail, name="detail"),
    path("delete/<int:pk>/", views.delete, name="delete"),
    path("edit/<int:pk>/", views.edit, name="edit"),
    path("update/<int:pk>/", views.update, name="update"),
]

pair/reviews/models.py
from email.policy import default
from django.db import models

# Create your models here.
class Review(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    star = models.FloatField(default=1.0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

pair/reviews/views.py
from django.shortcuts import render, redirect
from .models import Review

# Create your views here.
def main(request):
    return render(request, "reviews/main.html")


def review(request):
    reviews_ = Review.objects.all()
    context = {
        "reviews": reviews_,
    }

    return render(request, "reviews/index.html", context)


def new(request):
    return render(request, "reviews/new.html")


def create(request):
    title_ = request.POST.get("title")
    star_ = request.POST.get("star")
    content_ = request.POST.get("content")

    Review.objects.create(title=title_, content=content_, star=star_)

    return redirect("reviews:review")


def detail(request, pk):
    movie_title = Review.objects.get(id = pk)

    context = {
        'review' : movie_title,
    }
    return render(request, "reviews/detail.html", context)

def delete(request, pk):
    Review.objects.get(id = pk).delete()

    return redirect("reviews:review")

def edit(request, pk):
    edit_review = Review.objects.get(id = pk)

    context = {
        'edit_review' : edit_review,
    }

    return render(request, "reviews/edit.html", context)

def update(request, pk):
    # 업데이트를 할 애를 받아오고 id pk
    target = Review.objects.get(id = pk)
    title = request.POST.get("title")
    star = request.POST.get("star")
    content = request.POST.get("content")

    target.title = title
    target.star = star 
    target.content = content

    target.save()

    return redirect("reviews:review")

pair/reviews/templates/reviews/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex align-items-start mx-2" style="height: 100vh;">
  <div class="container bg-light" style="border-radius: 2rem; box-shadow: 2px 3px 7px rgba(0, 0, 0, 0.493);">
    <div class="p-3">
      <h2 class="fw-bolder" style="letter-spacing: -1px;">{{ review.title }}</h2> 
      <hr>
      <div class="bg-white mb-4" style="border: 1px solid rgba(96, 91, 91, 0.645); border-radius: .5rem;">
        <p class="p-3">{{ review.content }}</p>
      </div>
      <!-- 뷰포인트 lg 밑 -->
      <div class="d-block d-lg-none">
        <div class="d-flex flex-column align-items-center">
          <a href="{% url 'reviews:edit' review.id %}" class="btn form-control btn-secondary mb-3"><i class="bi bi-pencil-square"></i> 리뷰 수정</a>
          <a href="{% url 'reviews:review' %}" class="btn btn-dark form-control mb-3"><i class="bi bi-arrow-90deg-left"></i> 돌아 가기</a> 
          <a href="{% url 'reviews:delete' review.id %}" class="btn btn-primary form-control text-white mb-3"><i class="bi bi-trash"></i> 리뷰 삭제</a>
        </div>
      </div>
      <!-- 뷰포인트 lg 부터 -->
      <div class="d-none d-lg-block">
        <div class="d-flex justify-content-end">
          <a href="{% url 'reviews:edit' review.id %}" class="btn btn-secondary me-3"><i class="bi bi-pencil-square"></i> 리뷰 수정</a>
          <a href="{% url 'reviews:review' %}" class="btn btn-dark me-3"><i class="bi bi-arrow-90deg-left"></i> 돌아 가기</a>
          <a href="{% url 'reviews:delete' review.id %}" class="btn btn-primary text-white me-3"><i class="bi bi-trash"></i> 리뷰 삭제</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

pair/reviews/templates/reviews/edit.html
{% extends 'base.html' %}

{% block content %}
<div class="m-5">
  <div class="d-flex align-items-center">
    <h1 class="fw-light me-3 mb-0">글 수정하기</h1>
    <span><a href="{% url 'reviews:review' %}" class="btn btn-outline-dark align-middle"><i class="bi bi-x-lg"></i> 취소 하기</a></span>
  </div>
  <hr>
  <form action="{% url 'reviews:update' edit_review.id %}" method="POST">
    {% csrf_token %}
    <div class="my-4">
      <label for="title" class="form-label fw-bolder"><h4>제목</h4></label>
      <input type="text" class="form-control" id="title" name="title" maxlength="80" value="{{ edit_review.title }}">
    </div>
    <div class="mt-4">
      <label class="form-label fw-bolder" for="star"><h4>평점</h4></label>
      <input id="star" name="star" class="rating rating-loading" data-show-clear="false" data-min="0" data-max="5" data-step="0.5" value="{{ edit_review.star }}">
    </div>
    <div class="mb-3">
      <label for="content" class="form-label fw-bolder"><h4>내용</h4></label>
      <textarea class="form-control" id="content" rows="3" name="content">{{ edit_review.content }}</textarea>
    </div>
    <div class="d-flex justify-content-end">
      <input type="submit" class="btn btn-primary" value="수정">
    </div>
  </form>
</div>
{% endblock %}

pair/reviews/templates/reviews/index.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-start align-items-center mt-5">
  <h1 class="fw-light">REVIEW</h1>
  <div class="ms-3">
    <a href="{% url 'reviews:main' %}" class="btn btn-outline-dark"><i class="bi bi-arrow-90deg-left"></i> HOME</a>
  </div>
</div>
<hr>
<table class="table align-middle mt-5">
  <thead>
    <tr>
      <!-- <th scope="col"></th> -->
      <th scope="col" style="width: 30rem; letter-spacing: -.7px">리뷰 제목</th>
      <th scope="col" style="width: 55rem; letter-spacing: -.7px">리뷰 평점</th>
      <th scope="col" class="text-center" style="width: 40rem; letter-spacing: -.7px">작성 시간</th>
    </tr>
  </thead>
  <tbody>
    {% for review in reviews %}
    <tr>
      <!-- <th scope="row" class="text-center" style="font-size: 15px;">{{ review.pk }}</th> -->
      <td class="fw-bolder">
        {% if review.title == '' %}
        <a href="{% url 'reviews:detail' review.id %}" class="text-decoration-none text-dark fw-normal"> - </a>
        {% else %}
        <a href="{% url 'reviews:detail' review.id %}" class="text-decoration-none text-dark fw-normal" style="letter-spacing: -.8px;">{{ review.title }}</a>
        {% endif %}
      </td>
      <td class="position-relative">
        <input class="rating rating-loading position-absolute" style="top: 5;" value="{{ review.star}}" data-min="0" data-max="5" data-step="0.5" data-disabled="true" data-show-clear="false" data-size="xs" style="top: 20;">
      </td>
      <td class="text-center" style="letter-spacing: -1px;">{{ review.created_at|date:'Y년 m월 d일' }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<div class="d-flex justify-content-end">
  <a href="{% url 'reviews:new' %}" class="btn btn-primary">리뷰 작성</a>
</div>
{% endblock %}

pair/reviews/templates/reviews/main.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex align-items-center justify-content-center mx-2" style="height: 100vh;">
  <div class="text-center">
    <h1 class="fw-light mb-3">Movie Review</h1>
    <p><a href="{% url 'reviews:review' %}" class="btn btn-primary">GO !</a></p>
  </div>
</div>
{% endblock %}

pair/reviews/templates/reviews/new.html
{% extends 'base.html' %}

{% block content %}
<div class="m-5">
  <div class="d-flex align-items-center">
    <h1 class="fw-light me-3 mb-0">글 작성</h1>
    <span class="align-middle"><a href="{% url 'reviews:review' %}" class="btn btn-outline-dark align-middle"><i class="bi bi-arrow-90deg-left"></i> 뒤로 가기</a></span>
  </div>
  <hr>
  <form action="{% url 'reviews:create' %}" method="POST">
    {% csrf_token %}
    <div class="my-4">
      <label for="title" class="form-label fw-bolder"><h4>제목</h4></label>
      <input type="text" class="form-control" id="title" name="title" maxlength="80">
    </div>
    <div class="mt-4">
      <label class="form-label fw-bolder" for="star"><h4>평점</h4></label>
      <input id="star" name="star" class="rating rating-loading" data-show-clear="false" data-min="0" data-max="5" data-step="0.5" value="5">
    </div>
    <div class="mb-3">
      <label for="content" class="form-label fw-bolder"><h4>내용</h4></label>
      <textarea class="form-control" id="content" rows="3" name="content"></textarea>
    </div>
    <div class="d-flex justify-content-end">
      <input type="submit" class="btn btn-primary" value="작성">
    </div>
  </form>
</div>
{% endblock %}

pair/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>TODO</title>
  <!-- CSS only -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  <link href="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-star-rating@4.1.2/css/star-rating.min.css" media="all" rel="stylesheet" type="text/css" />
  <link href="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-star-rating@4.1.2/themes/krajee-svg/theme.css" media="all" rel="stylesheet" type="text/css" />
</head>

<body>
  <div class="container my-3" style="width: 100vw; height: 100vh;">
    {% block content %}
    {% endblock content %}
  </div>
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
    crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-star-rating@4.1.2/js/star-rating.min.js" type="text/javascript"></script>
  <script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-star-rating@4.1.2/themes/krajee-svg/theme.js"></script>
  <script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-star-rating@4.1.2/js/locales/LANG.js"></script>
</body>

</html>